Repository csvalpha/sofia, pull requests merged in 2022-10, with the labels that each got.

#793 fix: html manager fileMatch
  .github/renovate.json
Labels: bug

#794 refactor: update set-output commands to use GITHUB_OUTPUT
  .github/workflows/continuous-delivery.yml
  .github/workflows/publish-image.yml
Labels: refactor

#788 Update sentry to v7
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
  config/initializers/assets.rb
  package.json
  yarn.lock
Labels: dependencies

#800 refactor: change animate.css link to cdnjs
  app/views/layouts/application.html.erb
Labels: refactor

#799 feat(renovate.json): add regex manager for updating Sentry SDK
  .github/renovate.json
Labels: feature
