Repository csvalpha/sofia, pull requests merged in 2022-11, with the labels that each got.

#821 Update raven to sentry
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/jobs/sentry_job.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/sentry.rb
Labels: dependencies

#820 Bugfixes
  app/controllers/orders_controller.rb
  app/controllers/users_controller.rb
  app/javascript/packs/order_screen.js
Labels: critical

#772 fix: lint Vue files too
  .github/problem-matchers/eslint-stylish.json
  app/javascript/components/FlashNotification.vue
  app/javascript/components/ProductTable.vue
  app/javascript/components/UserInput.vue
  app/javascript/components/activity/ProductTotals.vue
  app/javascript/components/activity/producttotals.vue
  app/javascript/components/orderscreen/ActivityOrders.vue
  app/javascript/components/orderscreen/UserSelection.vue
  app/javascript/components/user/ActivityOrderHistory.vue
  app/javascript/components/user/OrderHistory.vue
  app/javascript/components/user/UsersTable.vue
  app/javascript/components/user/activityorderhistory.vue
  app/javascript/components/user/orderhistory.vue
  app/javascript/components/user/userstable.vue
  app/javascript/components/userinput.vue
  app/javascript/packs/activity.js
  app/javascript/packs/credit_mutations.js
  app/javascript/packs/invoices.js
  app/javascript/packs/order_screen.js
  app/javascript/packs/user.js
  app/javascript/packs/users.js
  app/views/activities/order_screen.html.erb
  package.json
Labels: bug
